# Generated by Django 4.0.4 on 2022-05-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(max_length=15)),
                ('std_name', models.CharField(max_length=25)),
                ('std_mail', models.CharField(max_length=30)),
                ('std_phone', models.IntegerField(max_length=10)),
            ],
        ),
    ]
