# Generated by Django 4.0.4 on 2022-05-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_data',
            name='std_info',
            field=models.CharField(default='please type something about you...', max_length=100),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='std_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='std_mail',
            field=models.EmailField(max_length=30),
        ),
    ]
