# Generated by Django 4.0.4 on 2022-05-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_student_data_std_info_alter_student_data_std_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='std_phone',
            field=models.IntegerField(),
        ),
    ]
