# Generated by Django 4.0.4 on 2022-06-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_student_data_std_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_data',
            name='std_link',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
