# Generated by Django 4.0.4 on 2022-06-15 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_student_data_std_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_data',
            old_name='std_link',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='student_data',
            old_name='std_mail',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='student_data',
            old_name='std_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='student_data',
            old_name='std_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='student_data',
            old_name='std_id',
            new_name='uid',
        ),
    ]
