# Generated by Django 4.0.4 on 2022-06-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_rename_std_link_student_data_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_data',
            name='add1',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
