# Generated by Django 4.0.4 on 2022-06-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_student_data_add1'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_data',
            name='add2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student_data',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
