# Generated by Django 4.0.4 on 2022-11-23 14:48

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_alter_student_data_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='proxy_student_data',
            fields=[
            ],
            options={
                'ordering': ['name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app1.student_data',),
            managers=[
                ('proxy_std_obj', django.db.models.manager.Manager()),
            ],
        ),
    ]
