# Generated by Django 3.1.7 on 2022-12-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_proxy_student_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
