# Generated by Django 4.0.4 on 2022-12-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_auto_20221202_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
