# Generated by Django 4.0.4 on 2022-06-13 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student_details',
            new_name='student_detail',
        ),
    ]
