# Generated by Django 4.0.4 on 2022-05-31 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='data_entry',
        ),
    ]
