# Generated by Django 4.0.4 on 2022-08-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='daughter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('middle_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('age', models.IntegerField(max_length=2)),
                ('dob', models.DateField()),
                ('phone', models.IntegerField()),
                ('home_addr', models.CharField(max_length=50)),
                ('school_addr', models.CharField(max_length=50)),
                ('pocket_money', models.IntegerField(max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='father',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('middle_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('age', models.IntegerField(max_length=2)),
                ('dob', models.DateField()),
                ('phone', models.IntegerField()),
                ('home_addr', models.CharField(max_length=50)),
                ('work_addr', models.CharField(max_length=50)),
                ('salary', models.IntegerField(max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='mother',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('middle_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('age', models.IntegerField(max_length=2)),
                ('dob', models.DateField()),
                ('phone', models.IntegerField()),
                ('home_addr', models.CharField(max_length=50)),
                ('home_expenses', models.IntegerField(max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='son',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('middle_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('age', models.IntegerField(max_length=2)),
                ('dob', models.DateField()),
                ('phone', models.IntegerField()),
                ('home_addr', models.CharField(max_length=50)),
                ('school_addr', models.CharField(max_length=50)),
                ('pocket_money', models.IntegerField(max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
