# Generated by Django 4.0.4 on 2022-08-12 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daughter',
            name='age',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='daughter',
            name='pocket_money',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(5000)]),
        ),
        migrations.AlterField(
            model_name='father',
            name='age',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='father',
            name='salary',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AlterField(
            model_name='mother',
            name='age',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='mother',
            name='home_expenses',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='son',
            name='age',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='son',
            name='pocket_money',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(5000)]),
        ),
    ]
