# Generated by Django 4.0.4 on 2022-08-12 16:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0002_alter_daughter_age_alter_daughter_pocket_money_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='son',
            old_name='school_addr',
            new_name='work_addr',
        ),
        migrations.RemoveField(
            model_name='son',
            name='pocket_money',
        ),
        migrations.AddField(
            model_name='son',
            name='salary',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(1000000)]),
            preserve_default=False,
        ),
    ]
