# Generated by Django 4.0.4 on 2022-08-12 17:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0003_rename_school_addr_son_work_addr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='daughter_in_law',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('middle_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('age', models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(100)])),
                ('dob', models.DateField()),
                ('phone', models.IntegerField()),
                ('home_addr', models.CharField(max_length=50)),
                ('home_expenses', models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(100000)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='grandson',
            fields=[
                ('son_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app4.son')),
                ('school_addr', models.CharField(max_length=50)),
                ('pocket_money', models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(5000)])),
            ],
            options={
                'abstract': False,
            },
            bases=('app4.son',),
        ),
    ]
