# Generated by Django 4.0.4 on 2022-08-12 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0004_daughter_in_law_grandson'),
    ]

    operations = [
        migrations.CreateModel(
            name='grandson1',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app4.grandson',),
        ),
    ]
