# Generated by Django 4.0.4 on 2022-06-29 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomTeam',
        ),
    ]
