# Generated by Django 4.0.4 on 2022-07-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0002_delete_customteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='team_members',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
