# Generated by Django 4.0.4 on 2022-07-01 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0003_customuser_team_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='team_members',
        ),
    ]
