# Generated by Django 4.0.4 on 2022-07-01 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0005_customteam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomTeam',
        ),
    ]
